### ISSUE TITLE
Veraltete Verwendung von TsConfig

### ISSUE THREAD

**Issue by thomasscheuermann** [fabianlipp/dpsgwue_default_upload_folder#2]
Seit der Version 9 ist die Nutzung von TsConfig veraltet und wird mit der Version 10 nicht mehr funktionieren.
https://github.com/beechit/default_upload_folder/issues/17

**Comment by fabianlipp** [comment]
Solved with commit fe33526da4ff84e7802ace324de66dafea019a21
